/** Full subcontract agreement text — used in the induction form and signed PDF. */
export const SUBCONTRACT_AGREEMENT_LINES: string[] = [
  'This agreement is entered into between Glyn Jenkins LTD (the "Company") and the operative named in this registration form (the "Subcontractor").',
  '',
  '## 1. STATUS',
  'The Subcontractor agrees to provide services to the Company as a self-employed subcontractor and not as an employee. The Subcontractor is responsible for their own tax affairs and National Insurance contributions, subject to the Construction Industry Scheme (CIS) where applicable.',
  '',
  '## 2. PAYMENT',
  'Payment will be made on a fortnightly basis, subject to work being completed to the satisfaction of the Company\'s Foreman and approved by the Company\'s administration. Gross amounts are agreed per lift or stage as set out in the price schedule for each site. Deductions including CIS tax (where applicable), admin fees, and insurance fees will be applied before net payment is made.',
  '',
  '## 3. CONSTRUCTION INDUSTRY SCHEME (CIS)',
  'Where the Subcontractor is registered under CIS at the standard 20% deduction rate, the Company will deduct 20% from the taxable element of each payment and submit this to HMRC on the Subcontractor\'s behalf. Gross-status subcontractors will receive payment without CIS deduction, subject to valid HMRC gross-status verification.',
  '',
  '## 4. ADMIN FEE',
  'A fortnightly administration fee as set by the Company will be deducted from each payment to cover payroll processing and administrative costs.',
  '',
  '## 5. INSURANCE',
  'The Subcontractor declares whether they hold their own public liability insurance. Where they do not, a company insurance fee as set by the Company will be deducted from each payment.',
  '',
  '## 6. CSCS COMPLIANCE',
  'The Subcontractor confirms their CSCS card is valid and will remain valid throughout their engagement. The Company reserves the right to suspend access to site if the CSCS card expires.',
  '',
  '## 7. RIGHT TO WORK',
  'The Subcontractor confirms they have the legal right to work in the United Kingdom and that all documents submitted are genuine and belong to them.',
  '',
  '## 8. CONDUCT & SAFETY',
  'The Subcontractor agrees to comply with all site health and safety rules, follow instructions from the Foreman, and conduct themselves professionally at all times. Failure to comply may result in immediate removal from site and suspension of payment.',
  '',
  '## 9. TERMINATION & SUBSTANDARD WORK',
  'Either party may terminate this agreement with reasonable notice. The Company reserves the right to terminate immediately in cases of gross misconduct, safety breaches, or fraudulent claims. Where work is deemed to be substandard or defective, the Company reserves the right to withhold payment, in full or in part, to cover the reasonable cost of remediation. Withheld payment will be released in full once the work has been inspected and passed to the required standard.',
  '',
  '## 10. GOVERNING LAW',
  'This agreement is governed by the laws of England and Wales.',
  '',
  '## SUBCONTRACTOR STATUS DECLARATION',
  'This Declaration forms part of the Self-Employed Subcontractor Agreement between Glyn Jenkins Ltd and the Subcontractor.',
  '',
  '## Self-Employment Status',
  '1. I have freely chosen to operate as a self-employed subcontractor and have not been required by Glyn Jenkins Ltd to do so.',
  '2. I understand that I am not an employee, worker, partner, agent or representative of Glyn Jenkins Ltd.',
  '3. I understand that I am not entitled to: Holiday pay; Sick pay; Pension contributions; Redundancy pay; Notice pay; Maternity or paternity pay; or any other employment-related rights or benefits.',
  '',
  '## Taxation',
  '4. I confirm that I am responsible for my own Income Tax, National Insurance Contributions and any other personal tax liabilities.',
  '5. I understand that Glyn Jenkins Ltd may make deductions under the Construction Industry Scheme (CIS) where required by law.',
  '6. I understand that CIS deductions do not create an employment relationship between myself and Glyn Jenkins Ltd.',
  '7. I understand that I remain responsible for submitting my own Self Assessment tax returns and dealing directly with HMRC regarding my personal tax affairs.',
  '',
  '## Business Independence',
  '8. I am operating as an independent business undertaking.',
  '9. I am free to work for other contractors, businesses and clients at any time.',
  '10. I understand that Glyn Jenkins Ltd is under no obligation to offer me work.',
  '11. I understand that I am under no obligation to accept work offered by Glyn Jenkins Ltd.',
  '12. I acknowledge that there is no guarantee of future work.',
  '13. I understand that each plot, phase, work package or instruction represents a separate engagement.',
  '',
  '## Substitution',
  '14. I understand that I may provide a suitably qualified substitute in accordance with the terms of the Agreement.',
  '15. I remain fully responsible for the performance, supervision and payment of any substitute provided by me.',
  '',
  '## Quality, Defects and Snagging',
  '16. I understand that I remain responsible for the quality of all works completed by me.',
  '17. I agree to rectify defective workmanship, incomplete works and snagging items attributable to my works.',
  '18. I acknowledge that Glyn Jenkins Ltd may retain reasonable sums from monies due to me in order to: complete outstanding works; rectify defective workmanship; complete snagging items; remedy non-compliant work; and recover reasonable losses arising from defective work.',
  '19. I acknowledge that any deductions made shall be limited to reasonable costs actually incurred by Glyn Jenkins Ltd.',
  '',
  '## Insurance and Administration Charges',
  '20. I understand that I am responsible for maintaining appropriate insurance where required.',
  '21. Where I elect to utilise insurance arrangements made available by Glyn Jenkins Ltd, I agree that a reasonable charge may be deducted from monies due to me.',
  '22. I acknowledge that Glyn Jenkins Ltd may charge reasonable administration fees relating to: CIS administration; payment processing; production of payment statements; workforce administration; compliance administration; and digital management systems.',
  '23. I understand that such charges do not create an employment relationship between myself and Glyn Jenkins Ltd.',
  '',
  '## General Declaration',
  '24. I have read and understood the Self-Employed Subcontractor Agreement.',
  '25. I have been given the opportunity to seek independent legal, tax or financial advice prior to signing.',
  '26. I confirm that all information provided by me is true and accurate.',
  '27. I acknowledge that this Declaration forms part of the contractual arrangements between myself and Glyn Jenkins Ltd.',
  '28. I understand and accept that failure to comply with the terms of the Agreement may result in deductions being made in accordance with the Agreement or termination of future work opportunities.',
  '',
  'Confirmation: By signing this Declaration and the Self-Employed Subcontractor Agreement, I confirm that I have read, understood and voluntarily accepted all terms and conditions contained within both documents and acknowledge that I am entering into the Agreement as an independent self-employed subcontractor.',
]
